"""new fields in user model

Revision ID: 836f565291e2
Revises: b05a68d4924b
Create Date: 2025-06-15 19:56:55.071773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836f565291e2'
down_revision = 'b05a68d4924b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
